---
game: !ruby/hash:Sinatra::IndifferentHash
  category: Other
  description: |-
    There are many slices of places in between. Spaces where people are trapped by things or people that have their own agenda. This space has been named Lacunae and is controlled by the Twelve. They sit in judgement, watch the lost souls relive their lives, trying to make a difference. Can you change your past, rebuild yourself into a better future? Can you escape this space in between to try again in the real world? Are you ready to square off against beings that are far beyond anything you've seen before?

    Lacunae is a sandbox game where original characters from other settings are welcome. We highly encourage our players to tell the stories of their favored characters, finding new solutions to old stories, or flip things completely and find a new path. Have you ever had a character where you were sad to see their story end? Now you have an opportunity to bring them back and find the story you want to share.

    Please visit our FAQ or log in to speak with staff if you have any questions.
  name: Lacunae
  public_game: false
  website: https://lacunae.aresmush.com
  status: Alpha
