---
who:
  where_style: scene
  who_fields:
  - field: status
    width: 7
    title: Status
  - field: name
    width: 20
    title: Name
  - field: group
    value: position
    width: 34
    title: Position
  - field: connected
    width: 7
    title: Conn
  - field: idle
    width: 4
    title: Idle
